version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
      - "22:22"
    volumes:
      - ./app:/app
      - ./pyproject.toml:/pyproject.toml
      - ./.env:/.env
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --reload"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:14
    env_file:
      - ./.env
    volumes:
      - db-data-pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data-pg: