version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
      - "22:22"
    volumes:
      - ./app:/app
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --reload"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
